name: Slack Webhook
on:
  push:
    branches:
      - gh-pages
jobs:
  Announce-On-Slack:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -H 'Content-type: application/json' --data '{"text":"A new update has been deployed on the Pixelgrade LT Roadmap!"}' https://hooks.slack.com/services/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
