name: Slack Webhook
on:
  push:
    branches:
      - gh-pages
jobs:
  Announce-On-Slack:
    runs-on: ubuntu-latest
    steps:
      - name: Announce new deploy to roadmap repo on Slack
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: "{\"text\":\"Hello World\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
